export const SET_RESTAURANT = "SET_RESTAURANT";
export const SET_STATE_LOADING_ALERT = "SET_STATE_LOADING_ALERT";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_CART = "CLEAR_CART";

